version: 1.0
provider:
  name: openfaas
  gateway: ${OPENFAAS_GATEWAY_URL:-http://localhost:31112}
functions:
  message-queue-spike:
    namespace: ${OPENFAAS_NAMESPACE:-dev}
    lang: node-hasura
    handler: ./Function
    image: shopozor/message-queue-spike-fn:${IMG_TAG:-latest}
    annotations:
      topic: staging.payment.authorization
configuration:
  templates:
    - name: node-hasura
      source: http://gitlab.hidora.com/softozor/shopozor/faas-templates.git
